baseURL = "https://edxu96.github.io/"
title = "北欧华人诗社"
copyright = "Copyright © 2008–2020, 北欧华人诗社; all rights reserved."
paginate = 2
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "最新诗刊"
    name = "最新诗刊"
    url = "/"
    weight = 10
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 0
  [[menu.main]]
    identifier = "会员风采"
    name = "会员风采"
    url = "/会员风采/"
    weight = 0
  [[menu.main]]
    identifier = "活动介绍"
    name = "活动介绍"
    url = "/活动介绍/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "北欧诗刊编辑部"
  description = "Nordic Chinese Poetry Asso. (NOCHPA)"
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "example@example.com"
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # stack-overflow = "https://stackoverflow.com"
    # instagram = "https://stackoverflow.com"
    # github = "https://github.com"
    # weibo = "https://www.weibo.com"
    # medium = "https://medium.com"
    # pinterest = "https://pinterest.com"
    # reddit = "https://reddit.com"
    # gitlab = "https://gitlab.com"
    # mastodon = "https://mastodon.social"
    # keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
